# Generated by Django 4.2.1 on 2023-05-30 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_address_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='defult',
            new_name='default',
        ),
    ]
